# Generated by Django 3.2.5 on 2021-07-31 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 8, 1, 0, 52, 33, 491785))),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.TextField(max_length=250, verbose_name='question_txt')),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'forum question',
                'verbose_name_plural': 'forum questions',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 8, 1, 0, 52, 33, 492782))),
                ('content', models.TextField(max_length=250, verbose_name='comment_txt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question')),
            ],
            options={
                'verbose_name': 'forum comment',
                'verbose_name_plural': 'forum comments',
                'db_table': 'comment',
            },
        ),
    ]
