# Generated by Django 3.2.5 on 2021-08-01 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210801_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 16, 6, 58, 71002)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 16, 6, 58, 69007)),
        ),
    ]
